import img1 from '../assets/img/property/image 1.jpg';
import img2 from '../assets/img/property/image 2.jpg';
import img3 from '../assets/img/property/image 3.jpg';
import img4 from '../assets/img/property/image 4.jpg';

export const properties = [
  {
    id: 1,
    image: img1,
    name: 'Villa Hijau Indah',
    price: '2.500.000.000',
    type: 'Rumah',
    area: '300 m²',
    description: 'Villa mewah dengan pemandangan alam yang menakjubkan.',
    address: 'Jl. Raya Indah No. 123, Kota Hijau',
    accessRoad: 'Akses jalan utama, dekat dengan pusat kota',
    landCertificate: 'SHM',
  },
  {
    id: 2,
    image: img2,
    name: 'Apartemen Megah Sentral',
    price: '1.200.000.000',
    type: 'Apartemen',
    area: '80 m²',
    description: 'Apartemen modern dengan fasilitas lengkap.',
    address: 'Jl. Pusat Kota No. 45, Kota Sentral',
    accessRoad: 'Akses mudah dari jalan tol utama',
    landCertificate: 'SHGB',
  },
  {
    id: 3,
    image: img3,
    name: 'Tanah Kebun Subur',
    price: '500.000.000',
    type: 'Tanah',
    area: '1000 m²',
    description: 'Tanah subur cocok untuk pertanian atau kebun.',
    address: 'Desa Makmur, Kecamatan Subur',
    accessRoad: 'Akses jalan tanah yang dapat dilalui kendaraan',
    landCertificate: 'SHGB',
  },
  {
    id: 4,
    image: img4,
    name: 'Rumah Nyaman Asri',
    price: '3.800.000.000',
    type: 'Rumah',
    area: '500 m²',
    description: 'Rumah dengan taman indah di lingkungan tenang.',
    address: 'Perumahan Asri No. 10, Kota Nyaman',
    accessRoad: 'Akses jalan utama, dekat dengan fasilitas umum',
    landCertificate: 'SHM',
  },
  {
    id: 5,
    image: img1,
    name: 'Apartemen Vista Indah',
    price: '1.800.000.000',
    type: 'Apartemen',
    area: '120 m²',
    description: 'Apartemen dengan pemandangan kota yang memukau.',
    address: 'Jl. Indah Vista No. 7, Kota Megah',
    accessRoad: 'Akses dekat dengan stasiun kereta api',
    landCertificate: 'SHM',
  },
  {
    id: 6,
    image: img2,
    name: 'Ruko Bisnis Makmur',
    price: '4.000.000.000',
    type: 'Ruko',
    area: '200 m²',
    description: 'Ruko strategis di pusat bisnis perkotaan.',
    address: 'Jl. Bisnis Makmur No. 25, Kota Bisnis',
    accessRoad: 'Akses jalan raya besar, parkir luas',
    landCertificate: 'SHGB',
  },
  {
    id: 7,
    image: img3,
    name: 'Kebun Jeruk Cerah',
    price: '600.000.000',
    type: 'Kebun',
    area: '5000 m²',
    description: 'Kebun jeruk produktif dengan view pegunungan.',
    address: 'Desa Cerah, Kecamatan Terang',
    accessRoad: 'Akses jalan utama, dekat dengan pasar tradisional',
    landCertificate: 'SHM',
  },
  {
    id: 8,
    image: img4,
    name: 'Apartemen Elit Sentral',
    price: '2.800.000.000',
    type: 'Apartemen',
    area: '100 m²',
    description: 'Apartemen mewah dengan fasilitas lengkap.',
    address: 'Jl. Sentral No. 15, Kota Sentral',
    accessRoad: 'Akses mudah dari jalan tol utama',
    landCertificate: 'SHM',
  },
  {
    id: 9,
    image: img2,
    name: 'Rumah Asri Damai',
    price: '1.600.000.000',
    type: 'Rumah',
    area: '150 m²',
    description: 'Rumah dengan taman indah di lingkungan damai.',
    address: 'Perumahan Damai No. 8, Kota Damai',
    accessRoad: 'Akses jalan utama, dekat dengan fasilitas umum',
    landCertificate: 'SHGB',
  },
  {
    id: 10,
    image: img4,
    name: 'Kos Strategis Megah',
    price: '700.000.000',
    type: 'Kos',
    area: '400 m²',
    description: 'Kos strategis di pusat kota dengan penghasilan stabil.',
    address: 'Jl. Megah No. 12, Kota Megah',
    accessRoad: 'Akses dekat dengan transportasi umum',
    landCertificate: 'SHGB',
  },
];
